name: Deployment workflow
on:
    push:
      branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy pull rebuild and up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port:  22
          script: |
            cd ~/apps/portfolio2021
            git pull origin main
            pm2 stop kuhn-ar
            npm run build
            pm2 start pm2.json
